# fly.toml file generated for idopting-products on 2022-08-28T18:28:58-03:00

app = "idopting-products"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
